name: Packing

on:
  release:
    types: [published]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install Go
        shell: bash
        run: |
          sudo add-apt-repository ppa:longsleep/golang-backports
          sudo apt update
          sudo apt install golang-go

      - name: Build binary
        shell: bash
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -trimpath -ldflags "-w -s" -o go_telegram_forwarder_bot ./cmd/bot

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            go_telegram_forwarder_bot

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image and Upload to Aliyun
        shell: bash
        run: |
          docker build -t go_telegram_forwarder_bot:$VERSION --output=type=docker .
          docker version
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hongkong.aliyuncs.com
          docker tag go_telegram_forwarder_bot:$VERSION registry.cn-hongkong.aliyuncs.com/liki4/go_telegram_forwarder_bot:$VERSION
          docker push registry.cn-hongkong.aliyuncs.com/liki4/go_telegram_forwarder_bot:$VERSION